namespace: microserviceRoot

public:
  - web:3000

services:
  web:
    image: node:4
    volumes:
      - .:/microserviceRoot
    working_dir: /microserviceRoot
    environment:
      - "MICROSERVICEA_ENDPOINT=http://microserviceA:3000"
      - "MICROSERVICED_ENDPOINT=http://microserviceD:3000"
    command: [npm, start]

dependencies:
  - microserviceA
  - microserviceD

setup:
  - npm install
