namespace: microserviceRoot

public: web:3000

services:
  web:
    image: node:4
    volumes:
      - .:/microserviceRoot
    working_dir: /microserviceRoot
    environment:
      - "MICROSERVICEA_ENDPOINT=http://microservicea:3000"
      - "MICROSERVICED_ENDPOINT=http://microserviced:3000"
    command: [npm, start]

dependencies:
  - microserviceA
  - microserviceB # just for a failure test
  - microserviceD

setup:
  - npm install
