namespace: microserviceRoot

public: web:3000

services:
  web:
    image: node:4
    volumes:
      - ..:/microserviceRoot
    working_dir: /microserviceRoot
    command: [npm, run, start-mocks]

setup:
  - cd .. && npm install
